leap-year: False # not implemented
start-date: "16.03"
end-date: "15.04"
year: "2020"
hours: 60
daily-average: 5
daily-std: 2
starting-weekday: "monday"

skip-weekends: True
skip-dates: ["17.03", "04.04"]

start-of-day: 9.0
end-of-day: 20.0
lunch-break-start: 13.0
lunch-break-end: 14.5

input-file: "test.xlsx" # commented out due to XLNT bug
output-file: "output.xlsx"
date-column: 1 # = A
start-time-column: 2 # = B
end-time-column: 3 # = C
first-row: 14
